site_name: Open Robotics

nav:
  - 主页: index.md
  - 安装: installation.md
  - 教程: turtial.md

theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  name: material
  language: zh


extra_css:
  - stylesheets/site.css


markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true